const {
  REACT_APP_API_URL: API_URL,
  REACT_APP_AWS_BUCKET_URL: AWS_BUCKET_URL,
  REACT_APP_AWS_S3_BUCKET: AWS_S3_BUCKET,
  REACT_APP_AWS_REGION: AWS_REGION,
  REACT_APP_AWS_ACCESS_KEY: AWS_ACCESS_KEY,
  REACT_APP_AWS_SECRET_KEY: AWS_SECRET_KEY,
} = process.env;

export {
  AWS_BUCKET_URL, AWS_S3_BUCKET, AWS_REGION, AWS_ACCESS_KEY, AWS_SECRET_KEY,
};

export default API_URL;
